spring:
  application:
    name: spring-lab

server:
  port: 8080

app:
  owner: Nurstan Bauyrkhan
  group: IS-2411
  mail:
    from: no-reply@iitu.kz
    retry-count: 3
    timeout: 5s
    enabled: true
  locale:
    default-locale: ru
    supported:
      - ru
      - kk
      - en